;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        helm-M-x
        ))

(setq mc/cmds-to-run-once
      '(
        autopair-newline
        moz-send-defun-and-go
        ))
