;;; spacemacs-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from spacemacs-dark-theme.el

(register-definition-prefixes "spacemacs-dark-theme" '("spacemacs-dark"))


;;; Generated autoloads from spacemacs-light-theme.el

(register-definition-prefixes "spacemacs-light-theme" '("spacemacs-light"))


;;; Generated autoloads from spacemacs-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "spacemacs-theme" '("create-spacemacs-theme" "spacemacs-theme-" "true-color-p"))

;;; End of scraped data

(provide 'spacemacs-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; spacemacs-theme-autoloads.el ends here
