(deftheme tmtxt
  "Created 2014-04-23.")

(custom-theme-set-faces
 'tmtxt
 '(cursor ((t (:foreground "#042028" :background "#708183"))))
 '(error ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(escape-glyph-face ((t (:foreground "#c60007"))))
 '(fringe ((t (:foreground "#465a61" :background "#0a2832"))))
 '(linum ((t (:foreground "#465a61" :background "#0a2832"))))
 '(header-line ((t (:foreground "#708183" :background "#0a2832" :weight normal :slant normal :underline nil :inverse-video t))))
 '(highlight ((t (:background "#0a2832"))))
 '(hl-line ((t (:underline nil :background "#0a2832"))))
 '(isearch ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#bd3612" :background "#042028"))))
 '(isearch-fail ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#bd3612" :background "#042028"))))
 '(lazy-highlight ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#a57705" :background "#042028"))))
 '(link ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#5859b7"))))
 '(link-visited ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#c61b6e"))))
 '(menu ((t (:foreground "#708183" :background "#0a2832"))))
 '(minibuffer-prompt ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#259185"))))
 '(mode-line ((t (:foreground "#81908f" :background "#0a2832" :weight normal :slant normal :underline nil :inverse-video t :box nil))))
 '(mode-line-inactive ((t (:foreground "#52676f" :background "#0a2832" :weight normal :slant normal :underline nil :inverse-video t :box nil))))
 '(region ((t (:foreground "#465a61" :background "#042028" :weight normal :slant normal :underline nil :inverse-video t))))
 '(secondary-selection ((t (:background "#0a2832"))))
 '(shadow ((t (:foreground "#465a61"))))
 '(trailing-whitespace ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#c60007"))))
 '(vertical-border ((t (:foreground "#708183"))))
 '(comint-highlight-prompt ((t (:foreground "#2075c7"))))
 '(compilation-info ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(compilation-warning ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#bd3612"))))
 '(custom-button ((t (:foreground "#81908f" :background "#0a2832" :box (:line-width 2 :style released-button)))))
 '(custom-button-mouse ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#81908f" :background "#0a2832" :inherit custom-button))))
 '(custom-button-pressed ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#81908f" :background "#0a2832" :box (:line-width 2 :style pressed-button) :inherit custom-button-mouse))))
 '(custom-changed ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#2075c7" :background "#fcf4dc"))))
 '(custom-comment ((t (:foreground "#81908f" :background "#0a2832"))))
 '(custom-comment-tag ((t (:foreground "#81908f" :background "#0a2832"))))
 '(custom-documentation ((t (:inherit default))))
 '(custom-group-tag ((t (:foreground "#81908f"))))
 '(custom-group-tag-1 ((t ((:weight bold :slant normal :underline nil :inverse-video nil) :foreground "#81908f"))))
 '(custom-invalid ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#c60007" :background "#042028"))))
 '(custom-link ((t (:foreground "#5859b7"))))
 '(custom-state ((t (:foreground "#728a05"))))
 '(custom-variable-tag ((t (:foreground "#81908f"))))
 '(diff-added ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(diff-changed ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#a57705"))))
 '(diff-removed ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(diff-refine-change ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#2075c7" :background "#042028"))))
 '(diff-file-header ((t (:background "#042028"))))
 '(diff-header ((t (:foreground "#81908f" :background "#042028"))))
 '(ido-only-match ((t (:foreground "#728a05"))))
 '(ido-subdir ((t (:foreground "#2075c7"))))
 '(ido-first-match ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(emacs-wiki-bad-link-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#c60007"))))
 '(emacs-wiki-link-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#2075c7"))))
 '(emacs-wiki-verbatim-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#52676f"))))
 '(eshell-ls-archive ((t (:foreground "#c61b6e"))))
 '(eshell-ls-backup ((t (:foreground "#a57705"))))
 '(eshell-ls-clutter ((t (:foreground "#bd3612"))))
 '(eshell-ls-directory ((t (:foreground "#2075c7"))))
 '(eshell-ls-executable ((t (:foreground "#728a05"))))
 '(eshell-ls-missing ((t (:foreground "#c60007"))))
 '(eshell-ls-product ((t (:foreground "#a57705"))))
 '(eshell-ls-readonly ((t (:foreground "#81908f"))))
 '(eshell-ls-special ((t (:foreground "#5859b7"))))
 '(eshell-ls-symlink ((t (:foreground "#259185"))))
 '(eshell-ls-unreadable ((t (:foreground "#52676f"))))
 '(eshell-prompt ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(font-lock-builtin-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(font-lock-comment-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#465a61"))))
 '(font-lock-constant-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#259185"))))
 '(font-lock-function-name-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(font-lock-keyword-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(font-lock-string-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#259185"))))
 '(font-lock-type-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#a57705"))))
 '(font-lock-variable-name-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(font-lock-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(font-lock-doc-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#465a61"))))
 '(font-lock-doc-string-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#465a61"))))
 '(font-lock-color-constant-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(font-lock-comment-delimiter-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#465a61"))))
 '(font-lock-preprocessor-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#bd3612"))))
 '(font-lock-reference-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#259185"))))
 '(font-lock-negation-char-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(font-lock-other-type-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#bd3612"))))
 '(font-lock-special-keyword-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(font-lock-exit-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(font-lock-other-emphasized-face ((t (:weight bold :underline nil :inverse-video nil :foreground "#5859b7"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#a57705"))))
 '(info-xref ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#2075c7"))))
 '(info-xref-visited ((t (:foreground "#c61b6e" :inherit info-xref))))
 '(org-hide ((t (:foreground "#042028"))))
 '(org-todo ((t (:background "light green" :foreground "firebrick2" :inverse-video nil :underline nil :slant normal :weight bold))))
 '(org-done ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(org-todo-kwd-face ((t (:background "#042028" :foreground "#c60007"))))
 '(org-done-kwd-face ((t (:foreground "#728a05" :background "#042028"))))
 '(org-project-kwd-face ((t (:foreground "#5859b7" :background "#042028"))))
 '(org-waiting-kwd-face ((t (:foreground "#bd3612" :background "#042028"))))
 '(org-someday-kwd-face ((t (:foreground "#2075c7" :background "#042028"))))
 '(org-started-kwd-face ((t (:foreground "#a57705" :background "#042028"))))
 '(org-cancelled-kwd-face ((t (:foreground "#728a05" :background "#042028"))))
 '(org-delegated-kwd-face ((t (:foreground "#259185" :background "#042028"))))
 '(table-cell ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#708183" :background "#042028"))))
 '(outline-1 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(outline-2 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#259185"))))
 '(outline-3 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#a57705"))))
 '(outline-4 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(outline-5 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#708183"))))
 '(outline-6 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#465a61"))))
 '(outline-7 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#bd3612"))))
 '(outline-8 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5859b7"))))
 '(speedbar-button-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#81908f"))))
 '(speedbar-directory-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#bd3612"))))
 '(speedbar-file-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(speedbar-highlight-face ((t (:background "#0a2832"))))
 '(speedbar-selected-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#a57705"))))
 '(speedbar-separator-face ((t (:weight normal :slant normal :underline nil :inverse-video t))))
 '(speedbar-tag-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(show-paren-match ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#259185" :background "#0a2832"))))
 '(show-paren-mismatch ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007" :background "#465a61"))))
 '(widget-field ((t (:foreground "#81908f" :background "#0a2832" :box (:line-width 1 :color "#e9e2cb") :inherit default))))
 '(widget-single-line-field ((t (:inherit widget-field))))
 '(flymake-errline ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#c60007" :background "#042028"))))
 '(flymake-warnline ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007" :background "#042028"))))
 '(column-marker-1 ((t (:background "#465a61"))))
 '(column-marker-2 ((t (:background "#259185"))))
 '(column-marker-3 ((t (:background "#5859b7"))))
 '(jabber-activity-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(jabber-activity-personal-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(jabber-chat-error ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(jabber-chat-prompt-foreign ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(jabber-chat-prompt-local ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(jabber-chat-prompt-system ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(jabber-chat-text-foreign ((t (:foreground "#81908f"))))
 '(jabber-chat-text-local ((t (:foreground "#708183"))))
 '(jabber-chat-rare-time-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#728a05"))))
 '(jabber-roster-user-away ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#728a05"))))
 '(jabber-roster-user-chatty ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#bd3612"))))
 '(jabber-roster-user-dnd ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#c60007"))))
 '(jabber-roster-user-error ((t (:weight light :slant italic :foreground "#c60007"))))
 '(jabber-roster-user-offline ((t (:foreground "#465a61"))))
 '(jabber-roster-user-online ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(jabber-roster-user-xa ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#c61b6e"))))
 '(gnus-cite-1 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(gnus-cite-2 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#259185"))))
 '(gnus-cite-3 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#a57705"))))
 '(gnus-cite-4 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(gnus-cite-5 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#bd3612"))))
 '(gnus-cite-6 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5859b7"))))
 '(gnus-cite-7 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(gnus-cite-8 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#c61b6e"))))
 '(gnus-cite-9 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#52676f"))))
 '(gnus-cite-10 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#465a61"))))
 '(gnus-cite-11 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0a2832"))))
 '(gnus-group-mail-1 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#fcf4dc"))))
 '(gnus-group-mail-1-empty ((t (:foreground "#fcf4dc"))))
 '(gnus-group-mail-2 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#e9e2cb"))))
 '(gnus-group-mail-2-empty ((t (:foreground "#e9e2cb"))))
 '(gnus-group-mail-3 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c61b6e"))))
 '(gnus-group-mail-3-empty ((t (:foreground "#c61b6e"))))
 '(gnus-group-mail-low ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#52676f"))))
 '(gnus-group-mail-low-empty ((t (:foreground "#52676f"))))
 '(gnus-group-news-1 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#81908f"))))
 '(gnus-group-news-1-empty ((t (:foreground "#81908f"))))
 '(gnus-group-news-2 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(gnus-group-news-2-empty ((t (:foreground "#2075c7"))))
 '(gnus-group-news-low ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#5859b7"))))
 '(gnus-group-news-low-empty ((t (:foreground "#5859b7"))))
 '(gnus-emphasis-highlight-words ((t (:weight normal :slant normal :underline nil :inverse-video nil (:foreground "#a57705")))))
 '(gnus-header-content ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#465a61"))))
 '(gnus-header-from ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#52676f"))))
 '(gnus-header-name ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#465a61"))))
 '(gnus-header-newsgroups ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0a2832"))))
 '(gnus-header-subject ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(gnus-server-agent ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#fcf4dc"))))
 '(gnus-server-closed ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#81908f"))))
 '(gnus-server-denied ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#e9e2cb"))))
 '(gnus-server-offline ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(gnus-server-opened ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#259185"))))
 '(gnus-signature ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#465a61"))))
 '(gnus-splash ((t (:foreground "#e9e2cb"))))
 '(gnus-summary-cancelled ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(gnus-summary-high-ancient ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-high-read ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-read))))
 '(gnus-summary-high-ticked ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-ticked))))
 '(gnus-summary-high-undownloaded ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-undownloaded))))
 '(gnus-summary-high-unread ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-unread))))
 '(gnus-summary-low-ancient ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-low-read ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-low-unread ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-unread))))
 '(gnus-summary-low-ticked ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-low-undownloaded ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-normal-ancient ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(gnus-summary-normal-read ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#465a61"))))
 '(gnus-summary-normal-ticked ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(gnus-summary-normal-undownloaded ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#e9e2cb"))))
 '(gnus-summary-normal-unread ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(gnus-summary-selected ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#042028" :background "#a57705"))))
 '(message-mml ((t (:foreground "#2075c7"))))
 '(message-cited-text ((t (:foreground "#e9e2cb"))))
 '(message-separator ((t (:foreground "#fcf4dc"))))
 '(message-header-xheader ((t (:foreground "#5859b7"))))
 '(message-header-name ((t (:foreground "#259185"))))
 '(message-header-other ((t (:foreground "#c60007"))))
 '(message-header-newsgroups ((t (:weight bold :underline nil :inverse-video nil :foreground "#a57705"))))
 '(message-header-subject ((t (:foreground "#52676f"))))
 '(message-header-cc ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(message-header-to ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#81908f"))))
 '(paren-face ((t (:foreground "#465a61"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#259185"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#a57705"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#2075c7"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#c60007"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#728a05"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#2075c7"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#bd3612"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#c61b6e"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#708183"))))
 '(slime-error-face ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#c60007"))))
 '(slime-note-face ((t (:foreground "#a57705"))))
 '(slime-repl-inputted-output-face ((t (:foreground "#c60007"))))
 '(slime-repl-output-mouseover-face ((t (:box (:color "#fcf4dc")))))
 '(slime-style-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#bd3612"))))
 '(slime-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(whitespace-empty ((t (:foreground "#c60007"))))
 '(whitespace-hspace ((t (:foreground "#bd3612"))))
 '(whitespace-indentation ((t (:foreground "#0a2832"))))
 '(whitespace-space ((t (:foreground "#0a2832"))))
 '(whitespace-space-after-tab ((t (:foreground "#259185"))))
 '(whitespace-space-before-tab ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(whitespace-tab ((t (:foreground "#0a2832"))))
 '(whitespace-trailing ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007" :background "#0a2832"))))
 '(whitespace-highlight-face ((t (:foreground "#c60007" :background "#2075c7"))))
 '(whitespace-line ((t (:foreground "#c61b6e" :background "#042028"))))
 '(rcirc-my-nick ((t (:foreground "#2075c7"))))
 '(rcirc-nick-in-message ((t (:foreground "#bd3612"))))
 '(rcirc-other-nick ((t (:foreground "#728a05"))))
 '(rcirc-prompt ((t (:foreground "#a57705"))))
 '(rcirc-bright-nick ((t (:foreground "#c61b6e"))))
 '(rcirc-server ((t (:foreground "#81908f"))))
 '(rcirc-timestamp ((t (:foreground "#465a61"))))
 '(font-latex-warning-face ((t (:foreground "#c60007"))))
 '(font-latex-sectioning-5-face ((t (:foreground "#5859b7"))))
 '(flyspell-incorrect ((t (:foreground "#c60007"))))
 '(flyspell-duplicate ((t (:foreground "#a57705"))))
 '(helm-selection ((t (:background "#EEEEEE" :foreground "#242424" :underline t :height 1.25))))
 '(diredp-file-name ((t (:foreground "Green"))))
 '(diredp-file-suffix ((t (:foreground "highlightColor"))))
 '(bold ((t (:foreground "gray100" :weight bold))))
 '(org-level-1 ((t (:inherit outline-1 :height 2.0))))
 '(org-level-2 ((t (:inherit outline-2 :height 1.75))))
 '(org-level-3 ((t (:inherit outline-3 :height 1.5))))
 '(org-level-4 ((t (:inherit outline-4 :height 1.25))))
 '(twittering-username-face ((t (:foreground "#259185" :inverse-video nil :underline nil :slant normal :weight normal :height 1.5))))
 '(default ((t (:foreground "#708183" :background "#042028"))))
 '(helm-match ((t (:inherit match :foreground "light green")))))

(provide-theme 'tmtxt)
