(deftheme truong
  "Created 2016-02-17.")

(custom-theme-set-faces
 'truong
 '(default ((t (:family "Monaco" :foundry "nil" :width normal :height 120 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#708183" :background "#042028" :stipple nil :inherit nil))))
 '(cursor ((t (:foreground "#042028" :background "White"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#259185"))))
 '(highlight ((t (:background "#0a2832"))))
 '(region ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#465a61" :background "#042028"))))
 '(shadow ((t (:foreground "#465a61"))))
 '(secondary-selection ((t (:background "#0a2832"))))
 '(trailing-whitespace ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#c60007"))))
 '(font-lock-builtin-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(font-lock-comment-delimiter-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#465a61"))))
 '(font-lock-comment-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#465a61"))))
 '(font-lock-constant-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#259185"))))
 '(font-lock-doc-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#465a61"))))
 '(font-lock-function-name-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(font-lock-keyword-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#728a05"))))
 '(font-lock-negation-char-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(font-lock-preprocessor-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#bd3612"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#a57705"))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#bd3612"))))
 '(font-lock-string-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#259185"))))
 '(font-lock-type-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#a57705"))))
 '(font-lock-variable-name-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(font-lock-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight normal :slant normal :underline (:color foreground-color :style line) :inverse-video nil :foreground "#5859b7"))))
 '(link-visited ((t (:weight normal :slant normal :underline (:color foreground-color :style line) :inverse-video nil :foreground "#c61b6e"))))
 '(fringe ((t (:foreground "#465a61" :background "#0a2832"))))
 '(header-line ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#708183" :background "#0a2832"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:weight normal :slant normal :underline nil :box nil :inverse-video t :foreground "#81908f" :background "#0a2832"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:weight normal :slant normal :underline nil :box nil :inverse-video t :foreground "#52676f" :background "#0a2832"))))
 '(isearch ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#bd3612" :background "#042028"))))
 '(isearch-fail ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#bd3612" :background "#042028"))))
 '(lazy-highlight ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#a57705" :background "#042028"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'truong)
